import Head from 'next/head'
import Content from '../components/Content'
import Header from '../components/Header'
import requests from '../utiles/requests'

export default function Home({data}) {
  return (
    <div className="bg-[#06202A]">
      <Head>
        <title>Create Hulu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header/>
      <Content data={data}/>
    </div>
  )
}
 export async function getServerSideProps(context){
  const genre  = context.query.genre

  const request = await fetch(`https://api.themoviedb.org/3${requests[genre]?.url || requests.fetchTrending.url}`)
  const data = await request.json()
  

  return {
    props: { data }, // will be passed to the page component as props
  }
 }