import Head from "next/head";
import Content from "../components/Content";
import Header from "../components/Header";
import requests from "../utiles/requests";
import {useSearchData} from '../store/useSearchData'

export default function Home({ data }) {
  const newData = useSearchData(state => state.search);
  console.log(newData)
  return (
    <div className="bg-[#06202A]">
      <Head>
        <title>Create Hulu App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content data={data} newData={newData} />
    </div>
  );
}
export async function getServerSideProps(context) {
  const genre = context.query.genre;

  const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  );
  const data = await request.json();

  return {
    props: { data }, 
  };
}
